services:
  redis:
    image: redis:8-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  orders-db:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: ${ORDERS_DB_NAME}
      POSTGRES_USER: ${ORDERS_DB_USER}
      POSTGRES_PASSWORD: ${ORDERS_DB_PASSWORD}
    ports:
      - "${ORDERS_DB_PORT}:5432"
    volumes:
      - ./order-service/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${ORDERS_DB_USER} -d ${ORDERS_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  payments-db:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: ${PAYMENTS_DB_NAME}
      POSTGRES_USER: ${PAYMENTS_DB_USER}
      POSTGRES_PASSWORD: ${PAYMENTS_DB_PASSWORD}
    ports:
      - "${PAYMENTS_DB_PORT}:5432"
    volumes:
      - ./payment-service/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PAYMENTS_DB_USER} -d ${PAYMENTS_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5

  payment-service:
    build: ./payment-service
    environment:
      DATABASE_URL: postgres://${PAYMENTS_DB_USER}:${PAYMENTS_DB_PASSWORD}@payments-db:5432/${PAYMENTS_DB_NAME}?sslmode=disable
      PORT: ${PAYMENT_SERVICE_PORT}
      PAYMENT_GRPC_PORT: ${PAYMENT_GRPC_PORT}
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      DEFAULT_CUSTOMER_EMAIL: ${DEFAULT_CUSTOMER_EMAIL}
    ports:
      - "${PAYMENT_SERVICE_PORT}:${PAYMENT_SERVICE_PORT}"
      - "${PAYMENT_GRPC_PORT}:${PAYMENT_GRPC_PORT}"
    depends_on:
      payments-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  notification-service:
    build: ./notification-service
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      SMTP_FROM: ${SMTP_FROM}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      REDIS_ADDR: redis:6379
      PROVIDER_MODE: ${PROVIDER_MODE:-REAL}
      RETRY_MAX: ${RETRY_MAX:-3}
      RETRY_BASE_DELAY_MS: ${RETRY_BASE_DELAY_MS:-2000}
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy

  order-service:
    build: ./order-service
    environment:
      DATABASE_URL: postgres://${ORDERS_DB_USER}:${ORDERS_DB_PASSWORD}@orders-db:5432/${ORDERS_DB_NAME}?sslmode=disable
      PAYMENT_GRPC_ADDR: payment-service:${PAYMENT_GRPC_PORT}
      PORT: ${ORDER_SERVICE_PORT}
      ORDER_GRPC_PORT: ${ORDER_GRPC_PORT}
      REDIS_ADDR: redis:6379
      CACHE_TTL_SECONDS: ${CACHE_TTL_SECONDS:-300}
      RATE_LIMIT_RPM: ${RATE_LIMIT_RPM:-10}
    ports:
      - "${ORDER_SERVICE_PORT}:${ORDER_SERVICE_PORT}"
      - "${ORDER_GRPC_PORT}:${ORDER_GRPC_PORT}"
    depends_on:
      orders-db:
        condition: service_healthy
      payment-service:
        condition: service_started
      redis:
        condition: service_healthy
